version: '3.7'
services:
  web:
    image: odoo:14.0
    container_name: "odoo14"
    # links:
    #   - postgres12
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./wasscom_addons_customs:/mnt/extra-addons
    environment:
      - HOST=postgres12
      - PORT=5432
      - USER=sotec
      - PASSWORD=sotec
    networks:
      - sotec
    restart: always
networks:
  sotec:
    external: true

# version: '3.7'
# services:
#   web:
#     image: odoo:14.0
#     ports:
#       - "8069:8069"
#     volumes:
#       - ./odoo-web-data:/var/lib/odoo
#       - ./config:/etc/odoo
#       - ./wasscom_addons_customs:/mnt/extra-addons
#     environment:
#       - HOST=postgres12
#       - PORT=5432
#       - USER=mitte
#       - PASSWORD=adminroot
#     networks:
#       - reseau_mitte
# networks:
#   reseau_mitte:
#     external: true

# version: '3.1'
# services:
#   web:
#     image: odoo:14.0
#     depends_on:
#       - db
#     ports:
#       - "8069:8069"
#     volumes:
#       - odoo-web-data:/var/lib/odoo
#       - ./config:/etc/odoo
#       - ./wasscom_addons_customs:/mnt/extra-addons
#     environment:
#       - HOST=db
#       - USER=odoo
#       - PASSWORD=myodoo
#   db:
#     image: postgres:12
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_PASSWORD=myodoo
#       - POSTGRES_USER=odoo
#       - PGDATA=/var/lib/postgresql/data/pgdata
#     volumes:
#       - odoo-db-data:/var/lib/postgresql/data/pgdata
# volumes:
#   odoo-web-data:
#   odoo-db-data:
